### ISSUE TITLE
Does not work for controllers/models and more?

### ISSUE THREAD

**Issue by tdegrunt** [aki77/vscode-rails-i18n#1]
Hello,

Awesome plugin!
We have translations in our error messages from validations, services, models and controllers, perhaps even more locations (anything under /app really?)

It doesn't seem to work for anything other than views?

Cheers,
Tom

**Comment by aki77** [comment]
Thanks.
Please tell us the expected behavior with sample code.

**Comment by tdegrunt** [comment]
Sure! 

In our models (app/models) for example we have code like this:
```ruby
[I18n.t('hub.kind.forward'), 'forward']
```

Or in app/validators we have:
```ruby
basket.errors.add(:base, I18n.t('activemodel.errors.messages.chosen_product_not_available'))
```

I would have expected this plugin to show the completion, hover and quick-fix for these too.

**Comment by aki77** [comment]
Does it work in view?

**Comment by tdegrunt** [comment]
Not always, either:
<img width="331" alt="Screenshot 2019-09-06 at 09 30 27" src="https://user-images.githubusercontent.com/46554/64409438-303e5880-d089-11e9-9d7a-95d4a2c9e35b.png">

It doesn't work for 'graph' here in this screenshot.

I have multiple files in my config/locales folder, some with the same language key (en):
en.yml
mobile.en.yml

Could this be the problem?

**Comment by aki77** [comment]
In my environment, it works as expected in all cases.
Can you have a minimal repository that reproduces the problem?

[![Image from Gyazo](https://i.gyazo.com/68c0550636b58078ebbc6a795368e19e.gif)](https://gyazo.com/68c0550636b58078ebbc6a795368e19e)

**Comment by tdegrunt** [comment]
Made this:
https://github.com/tdegrunt/vscode-rails-i18n

I have more luck with this simple case, but 'lazy lookups' in controller seem to fail:
https://guides.rubyonrails.org/i18n.html#lazy-lookup

See: app/controllers/books_controller.rb:9

Reading the extension source code, perhaps I have also wrongfully assumed I could see all used languages and QuickFix for missing translations.

**Comment by aki77** [comment]
Thank you for creating the repository.

> I have more luck with this simple case, but 'lazy lookups' in controller seem to fail:

This extension supports `lazy lookups` only in views.
I don't use `lazy lookups` because it is prone to trouble when moving files. :sweat:

**Comment by tdegrunt** [comment]
okay, thanks. at least it’s expected behavior then. Thanks for the plugin!
