### ISSUE TITLE
Doesn't work in views

### ISSUE THREAD

**Issue by akimthedream** [aki77/vscode-rails-i18n#12]
Hey :) First of all, very helpful extension, I like it a lot!

My only issue: It works perfectly fine in controllers, but not at all in views (using .html.erb). As it would be deactivated for views, no popups, no autocompletion, no jump to translation source etc... 

Any ideas? Thank you!

**Comment by aki77** [comment]
@akimthedream 

What language mode are you using to edit your ERB files?

![Image from Gyazo](https://i.gyazo.com/b4821dbfb411b327ef1797c78047b595.png)
